import { SIC_ALL, searchSic as _searchSic, isSicSymbol } from "./sic-catalog";
import { paysDividend } from "./dividend-payers";
export type MxKind = "stock" | "etf" | "fibra" | "bond_etf";
export type MxItem = { symbol: string; name: string; kind: MxKind; venue: "BMV" | "BIVA" | "SIC" | "BMV/BIVA" };
function m(rows: Array<[string, string, MxKind, MxItem["venue"]]>): MxItem[] {
  return rows.map(([symbol, name, kind, venue]) => ({ symbol, name, kind, venue }));
}
export const MX_LOCAL_STOCKS: MxItem[] = m([["AMXL.MX","América Móvil","stock","BMV/BIVA"],["AMXB.MX","América Móvil B","stock","BMV/BIVA"],["WALMEX.MX","Walmart de México","stock","BMV/BIVA"],["GFNORTEO.MX","GFNorte (Banorte)","stock","BMV/BIVA"],["GMEXICOB.MX","Grupo México","stock","BMV/BIVA"],["FEMSAUBD.MX","FEMSA","stock","BMV/BIVA"],["BIMBOA.MX","Bimbo","stock","BMV/BIVA"],["CEMEXCPO.MX","Cemex CPO","stock","BMV/BIVA"],["TLEVISACPO.MX","Televisa CPO","stock","BMV/BIVA"],["KIMBERA.MX","Kimberly-Clark de México","stock","BMV/BIVA"],["ASURB.MX","ASUR","stock","BMV/BIVA"],["GAPB.MX","GAP","stock","BMV/BIVA"],["OMAB.MX","OMA","stock","BMV/BIVA"],["GFINBURO.MX","Inbursa","stock","BMV/BIVA"],["BOLSAA.MX","Bolsa Mexicana de Valores","stock","BMV/BIVA"],["GCARSOA1.MX","Grupo Carso","stock","BMV/BIVA"],["GENTERA.MX","Gentera","stock","BMV/BIVA"],["ALSEA.MX","Alsea","stock","BMV/BIVA"],["AC.MX","Arca Continental","stock","BMV/BIVA"],["KOFUBL.MX","Coca-Cola FEMSA","stock","BMV/BIVA"],["PE&OLES.MX","Peñoles","stock","BMV/BIVA"],["ALFAA.MX","Alfa","stock","BMV/BIVA"],["ALPEKA.MX","Alpek","stock","BMV/BIVA"],["LIVEPOLC-1.MX","Liverpool","stock","BMV/BIVA"],["MEGACPO.MX","Megacable","stock","BMV/BIVA"],["ORBIA.MX","Orbia","stock","BMV/BIVA"],["PINFRA.MX","PINFRA","stock","BMV/BIVA"],["CUERVO.MX","Becle (José Cuervo)","stock","BMV/BIVA"],["GRUMAB.MX","Gruma","stock","BMV/BIVA"],["LABB.MX","Genomma Lab","stock","BMV/BIVA"],["BBAJIOO.MX","Banco del Bajío","stock","BMV/BIVA"],["CHDRAUIB.MX","Chedraui","stock","BMV/BIVA"],["VESTA.MX","Vesta","stock","BMV/BIVA"],["GCC.MX","GCC","stock","BMV/BIVA"],["RA.MX","Regional","stock","BMV/BIVA"],["Q.MX","Qualitas","stock","BMV/BIVA"],["AGUA.MX","Grupo Rotoplas","stock","BMV/BIVA"],["NEMAK.MX","Nemak","stock","BMV/BIVA"],["VOLAR.MX","Volaris","stock","BMV/BIVA"],["GFREGIOO.MX","Banregio","stock","BMV/BIVA"],["GPROFUT.MX","Grupo Profuturo","stock","BMV/BIVA"],["FRAGUAB.MX","Fragua","stock","BMV/BIVA"],["BACHOCOB.MX","Bachoco","stock","BMV/BIVA"],["HERDEZ.MX","Herdez","stock","BMV/BIVA"],["SORIANAB.MX","Organización Soriana","stock","BMV/BIVA"]]);
export const MX_FIBRAS: MxItem[] = m([["FUNO11.MX","Fibra UNO","fibra","BMV/BIVA"],["FMTY14.MX","Fibra Mty","fibra","BMV/BIVA"],["DANHOS13.MX","Fibra Danhos","fibra","BMV/BIVA"],["FIBRAPL14.MX","Fibra Prologis","fibra","BMV/BIVA"],["TERRA13.MX","Fibra Terra","fibra","BMV/BIVA"],["FSHOP13.MX","Fibra Shop","fibra","BMV/BIVA"],["FHIPO14.MX","FHipo","fibra","BMV/BIVA"],["FNOVA17.MX","Fibra Nova","fibra","BMV/BIVA"],["FIHO12.MX","Fibra Hotel","fibra","BMV/BIVA"],["STORAGE18.MX","Fibra Storage","fibra","BMV/BIVA"],["EDUCA18.MX","Fibra Educa","fibra","BMV/BIVA"],["FINN13.MX","Fibra Inn","fibra","BMV/BIVA"],["FPLUS16.MX","Fibra Plus","fibra","BMV/BIVA"],["FIBRAUP18.MX","Fibra Upsite","fibra","BMV/BIVA"],["FCFE18.MX","CFE Fibra E","fibra","BMV/BIVA"],["FMX23.MX","FMX23","fibra","BMV/BIVA"],["FEXI21.MX","Fibra EXI","fibra","BMV/BIVA"],["NEXT25.MX","Fibra NEXT","fibra","BMV/BIVA"]]);
export const MX_LOCAL_ETFS: MxItem[] = m([["NAFTRAC.MX","iShares NAFTRAC (IPC)","etf","BMV/BIVA"],["MEXTRAC.MX","MEXTRAC 09","etf","BMV/BIVA"],["ILCTRAC.MX","iShares IPC Large Cap TRAC","etf","BMV/BIVA"],["FIBRATC.MX","ETF S&P/BMV FIBRAS","etf","BMV/BIVA"],["VMEX.MX","Vanguard FTSE BIVA México","etf","BMV/BIVA"],["IVVPESO.MX","iShares S&P 500 MXN Hedged","etf","BMV/BIVA"],["CETETRC.MX","iShares CETETRAC","etf","BMV/BIVA"],["UDITRAC.MX","iShares UDITRAC","etf","BMV/BIVA"],["DIABLOI.MX","DIABLOI inverso IPC","etf","BMV/BIVA"]]);
export const MX_BOND_ETFS: MxItem[] = m([["LQD","iShares Corp. grado inversión","bond_etf","SIC"],["HYG","iShares High Yield","bond_etf","SIC"],["JNK","SPDR High Yield","bond_etf","SIC"],["BND","Vanguard Total Bond","bond_etf","SIC"],["AGG","iShares Core US Aggregate Bond","bond_etf","SIC"],["TIP","iShares TIPS","bond_etf","SIC"],["EMB","iShares USD Emerging Markets Bond","bond_etf","SIC"]]);
export const MX_UNIVERSE: MxItem[] = [...MX_LOCAL_STOCKS, ...MX_FIBRAS, ...MX_LOCAL_ETFS, ...MX_BOND_ETFS];
export function searchMx(q: string): MxItem[] {
  const n = q.trim().toUpperCase();
  if (!n) return MX_UNIVERSE;
  return MX_UNIVERSE.filter((i) => i.symbol.toUpperCase().includes(n) || i.name.toUpperCase().includes(n));
}
export { SIC_ALL, isSicSymbol, paysDividend };
export function searchUniverse(q: string) {
  return { local: searchMx(q), sic: _searchSic(q) };
}
