import { normalizeSearchText } from "./search-text";
/**
 * Catálogo del Sistema Internacional de Cotizaciones (SIC / Mercado Global BMV).
 * Tickers de origen (Yahoo/US) — en casas de bolsa MX se operan en pesos.
 * El SIC tiene ~3,500–3,700 valores; aquí van los más líquidos y consultados
 * más una base amplia de ETFs y acciones globales habituales en el SIC.
 */

import { normalizeYahooSymbol } from "./market-data/types";

export type SicKind = "stock" | "etf";

export type SicItem = {
  symbol: string;
  name: string;
  kind: SicKind;
  region: "US" | "EU" | "ASIA" | "LATAM" | "GLOBAL";
};

export const SIC_STOCKS: SicItem[] = [
  { symbol: "AAPL", name: "Apple", kind: "stock", region: "US" },
  { symbol: "MSFT", name: "Microsoft", kind: "stock", region: "US" },
  { symbol: "NVDA", name: "NVIDIA", kind: "stock", region: "US" },
  { symbol: "AMZN", name: "Amazon", kind: "stock", region: "US" },
  { symbol: "GOOGL", name: "Alphabet A", kind: "stock", region: "US" },
  { symbol: "GOOG", name: "Alphabet C", kind: "stock", region: "US" },
  { symbol: "META", name: "Meta Platforms", kind: "stock", region: "US" },
  { symbol: "TSLA", name: "Tesla", kind: "stock", region: "US" },
  { symbol: "AVGO", name: "Broadcom", kind: "stock", region: "US" },
  { symbol: "BRK-B", name: "Berkshire Hathaway B", kind: "stock", region: "US" },
  { symbol: "JPM", name: "JPMorgan Chase", kind: "stock", region: "US" },
  { symbol: "V", name: "Visa", kind: "stock", region: "US" },
  { symbol: "MA", name: "Mastercard", kind: "stock", region: "US" },
  { symbol: "LLY", name: "Eli Lilly", kind: "stock", region: "US" },
  { symbol: "UNH", name: "UnitedHealth", kind: "stock", region: "US" },
  { symbol: "XOM", name: "Exxon Mobil", kind: "stock", region: "US" },
  { symbol: "JNJ", name: "Johnson & Johnson", kind: "stock", region: "US" },
  { symbol: "WMT", name: "Walmart", kind: "stock", region: "US" },
  { symbol: "PG", name: "Procter & Gamble", kind: "stock", region: "US" },
  { symbol: "HD", name: "Home Depot", kind: "stock", region: "US" },
  { symbol: "COST", name: "Costco", kind: "stock", region: "US" },
  { symbol: "ABBV", name: "AbbVie", kind: "stock", region: "US" },
  { symbol: "MRK", name: "Merck", kind: "stock", region: "US" },
  { symbol: "KO", name: "Coca-Cola", kind: "stock", region: "US" },
  { symbol: "PEP", name: "PepsiCo", kind: "stock", region: "US" },
  { symbol: "CVX", name: "Chevron", kind: "stock", region: "US" },
  { symbol: "BAC", name: "Bank of America", kind: "stock", region: "US" },
  { symbol: "ORCL", name: "Oracle", kind: "stock", region: "US" },
  { symbol: "AMD", name: "Advanced Micro Devices", kind: "stock", region: "US" },
  { symbol: "NFLX", name: "Netflix", kind: "stock", region: "US" },
  { symbol: "ADBE", name: "Adobe", kind: "stock", region: "US" },
  { symbol: "CRM", name: "Salesforce", kind: "stock", region: "US" },
  { symbol: "CSCO", name: "Cisco", kind: "stock", region: "US" },
  { symbol: "INTC", name: "Intel", kind: "stock", region: "US" },
  { symbol: "QCOM", name: "Qualcomm", kind: "stock", region: "US" },
  { symbol: "TXN", name: "Texas Instruments", kind: "stock", region: "US" },
  { symbol: "AMAT", name: "Applied Materials", kind: "stock", region: "US" },
  { symbol: "MU", name: "Micron", kind: "stock", region: "US" },
  { symbol: "LRCX", name: "Lam Research", kind: "stock", region: "US" },
  { symbol: "NOW", name: "ServiceNow", kind: "stock", region: "US" },
  { symbol: "INTU", name: "Intuit", kind: "stock", region: "US" },
  { symbol: "IBM", name: "IBM", kind: "stock", region: "US" },
  { symbol: "CAT", name: "Caterpillar", kind: "stock", region: "US" },
  { symbol: "GE", name: "GE Aerospace", kind: "stock", region: "US" },
  { symbol: "HON", name: "Honeywell", kind: "stock", region: "US" },
  { symbol: "UNP", name: "Union Pacific", kind: "stock", region: "US" },
  { symbol: "BA", name: "Boeing", kind: "stock", region: "US" },
  { symbol: "RTX", name: "RTX", kind: "stock", region: "US" },
  { symbol: "LMT", name: "Lockheed Martin", kind: "stock", region: "US" },
  { symbol: "DIS", name: "Walt Disney", kind: "stock", region: "US" },
  { symbol: "CMCSA", name: "Comcast", kind: "stock", region: "US" },
  { symbol: "T", name: "AT&T", kind: "stock", region: "US" },
  { symbol: "VZ", name: "Verizon", kind: "stock", region: "US" },
  { symbol: "NKE", name: "Nike", kind: "stock", region: "US" },
  { symbol: "SBUX", name: "Starbucks", kind: "stock", region: "US" },
  { symbol: "MCD", name: "McDonald's", kind: "stock", region: "US" },
  { symbol: "LOW", name: "Lowe's", kind: "stock", region: "US" },
  { symbol: "TGT", name: "Target", kind: "stock", region: "US" },
  { symbol: "AMGN", name: "Amgen", kind: "stock", region: "US" },
  { symbol: "PFE", name: "Pfizer", kind: "stock", region: "US" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", kind: "stock", region: "US" },
  { symbol: "GILD", name: "Gilead", kind: "stock", region: "US" },
  { symbol: "ABT", name: "Abbott", kind: "stock", region: "US" },
  { symbol: "TMO", name: "Thermo Fisher", kind: "stock", region: "US" },
  { symbol: "DHR", name: "Danaher", kind: "stock", region: "US" },
  { symbol: "ISRG", name: "Intuitive Surgical", kind: "stock", region: "US" },
  { symbol: "MDT", name: "Medtronic", kind: "stock", region: "US" },
  { symbol: "SYK", name: "Stryker", kind: "stock", region: "US" },
  { symbol: "CVS", name: "CVS Health", kind: "stock", region: "US" },
  { symbol: "WFC", name: "Wells Fargo", kind: "stock", region: "US" },
  { symbol: "GS", name: "Goldman Sachs", kind: "stock", region: "US" },
  { symbol: "MS", name: "Morgan Stanley", kind: "stock", region: "US" },
  { symbol: "C", name: "Citigroup", kind: "stock", region: "US" },
  { symbol: "AXP", name: "American Express", kind: "stock", region: "US" },
  { symbol: "BLK", name: "BlackRock", kind: "stock", region: "US" },
  { symbol: "SCHW", name: "Charles Schwab", kind: "stock", region: "US" },
  { symbol: "SPGI", name: "S&P Global", kind: "stock", region: "US" },
  { symbol: "MMC", name: "Marsh McLennan", kind: "stock", region: "US" },
  { symbol: "CB", name: "Chubb", kind: "stock", region: "US" },
  { symbol: "PGR", name: "Progressive", kind: "stock", region: "US" },
  { symbol: "NEE", name: "NextEra Energy", kind: "stock", region: "US" },
  { symbol: "SO", name: "Southern Company", kind: "stock", region: "US" },
  { symbol: "DUK", name: "Duke Energy", kind: "stock", region: "US" },
  { symbol: "LIN", name: "Linde", kind: "stock", region: "US" },
  { symbol: "APD", name: "Air Products", kind: "stock", region: "US" },
  { symbol: "SHW", name: "Sherwin-Williams", kind: "stock", region: "US" },
  { symbol: "MMM", name: "3M", kind: "stock", region: "US" },
  { symbol: "DE", name: "Deere", kind: "stock", region: "US" },
  { symbol: "UPS", name: "UPS", kind: "stock", region: "US" },
  { symbol: "FDX", name: "FedEx", kind: "stock", region: "US" },
  { symbol: "MO", name: "Altria", kind: "stock", region: "US" },
  { symbol: "PM", name: "Philip Morris", kind: "stock", region: "US" },
  { symbol: "CL", name: "Colgate-Palmolive", kind: "stock", region: "US" },
  { symbol: "MDLZ", name: "Mondelez", kind: "stock", region: "US" },
  { symbol: "GIS", name: "General Mills", kind: "stock", region: "US" },
  { symbol: "KMB", name: "Kimberly-Clark", kind: "stock", region: "US" },
  { symbol: "O", name: "Realty Income", kind: "stock", region: "US" },
  { symbol: "PLD", name: "Prologis", kind: "stock", region: "US" },
  { symbol: "AMT", name: "American Tower", kind: "stock", region: "US" },
  { symbol: "CCI", name: "Crown Castle", kind: "stock", region: "US" },
  { symbol: "SPG", name: "Simon Property", kind: "stock", region: "US" },
  { symbol: "EQIX", name: "Equinix", kind: "stock", region: "US" },
  { symbol: "OXY", name: "Occidental Petroleum", kind: "stock", region: "US" },
  { symbol: "COP", name: "ConocoPhillips", kind: "stock", region: "US" },
  { symbol: "SLB", name: "Schlumberger", kind: "stock", region: "US" },
  { symbol: "APA", name: "APA Corp", kind: "stock", region: "US" },
  { symbol: "BABA", name: "Alibaba", kind: "stock", region: "ASIA" },
  { symbol: "PDD", name: "PDD Holdings", kind: "stock", region: "ASIA" },
  { symbol: "JD", name: "JD.com", kind: "stock", region: "ASIA" },
  { symbol: "NIO", name: "NIO", kind: "stock", region: "ASIA" },
  { symbol: "TSM", name: "TSMC", kind: "stock", region: "ASIA" },
  { symbol: "SONY", name: "Sony", kind: "stock", region: "ASIA" },
  { symbol: "TM", name: "Toyota", kind: "stock", region: "ASIA" },
  { symbol: "HMC", name: "Honda", kind: "stock", region: "ASIA" },
  { symbol: "SNE", name: "Sony (hist.)", kind: "stock", region: "ASIA" },
  { symbol: "ASML", name: "ASML", kind: "stock", region: "EU" },
  { symbol: "NVO", name: "Novo Nordisk", kind: "stock", region: "EU" },
  { symbol: "SAP", name: "SAP", kind: "stock", region: "EU" },
  { symbol: "SIE.DE", name: "Siemens", kind: "stock", region: "EU" },
  { symbol: "AIR.PA", name: "Airbus", kind: "stock", region: "EU" },
  { symbol: "MC.PA", name: "LVMH", kind: "stock", region: "EU" },
  { symbol: "OR.PA", name: "L'Oréal", kind: "stock", region: "EU" },
  { symbol: "NESN.SW", name: "Nestlé", kind: "stock", region: "EU" },
  { symbol: "ROG.SW", name: "Roche", kind: "stock", region: "EU" },
  { symbol: "NOVN.SW", name: "Novartis", kind: "stock", region: "EU" },
  { symbol: "UL", name: "Unilever", kind: "stock", region: "EU" },
  { symbol: "BP", name: "BP", kind: "stock", region: "EU" },
  { symbol: "SHEL", name: "Shell", kind: "stock", region: "EU" },
  { symbol: "AZN", name: "AstraZeneca", kind: "stock", region: "EU" },
  { symbol: "GSK", name: "GSK", kind: "stock", region: "EU" },
  { symbol: "RHHBY", name: "Roche ADR", kind: "stock", region: "EU" },
  { symbol: "NVS", name: "Novartis ADR", kind: "stock", region: "EU" },
  { symbol: "SNY", name: "Sanofi", kind: "stock", region: "EU" },
  { symbol: "ING", name: "ING Groep", kind: "stock", region: "EU" },
  { symbol: "SAN", name: "Banco Santander", kind: "stock", region: "EU" },
  { symbol: "BBVA", name: "BBVA", kind: "stock", region: "EU" },
  { symbol: "ITX.MC", name: "Inditex", kind: "stock", region: "EU" },
  { symbol: "VALE", name: "Vale", kind: "stock", region: "LATAM" },
  { symbol: "PBR", name: "Petrobras", kind: "stock", region: "LATAM" },
  { symbol: "ITUB", name: "Itaú Unibanco", kind: "stock", region: "LATAM" },
  { symbol: "BBD", name: "Bradesco", kind: "stock", region: "LATAM" },
  { symbol: "ABEV", name: "Ambev", kind: "stock", region: "LATAM" },
  { symbol: "MELI", name: "Mercado Libre", kind: "stock", region: "LATAM" },
  { symbol: "NU", name: "Nu Holdings", kind: "stock", region: "LATAM" },
  { symbol: "PLTR", name: "Palantir", kind: "stock", region: "US" },
  { symbol: "UBER", name: "Uber", kind: "stock", region: "US" },
  { symbol: "ABNB", name: "Airbnb", kind: "stock", region: "US" },
  { symbol: "SHOP", name: "Shopify", kind: "stock", region: "US" },
  { symbol: "PYPL", name: "PayPal", kind: "stock", region: "US" },
  { symbol: "SQ", name: "Block", kind: "stock", region: "US" },
  { symbol: "ARM", name: "Arm Holdings", kind: "stock", region: "US" },
// +100 liquidos habituales en SIC (alta operatividad relativa)
  { symbol: "NOC", name: "Northrop Grumman", kind: "stock", region: "US" },
  { symbol: "GD", name: "General Dynamics", kind: "stock", region: "US" },
  { symbol: "ADP", name: "Automatic Data Processing", kind: "stock", region: "US" },
  { symbol: "ADI", name: "Analog Devices", kind: "stock", region: "US" },
  { symbol: "KLAC", name: "KLA", kind: "stock", region: "US" },
  { symbol: "SNPS", name: "Synopsys", kind: "stock", region: "US" },
  { symbol: "CDNS", name: "Cadence Design", kind: "stock", region: "US" },
  { symbol: "PANW", name: "Palo Alto Networks", kind: "stock", region: "US" },
  { symbol: "CRWD", name: "CrowdStrike", kind: "stock", region: "US" },
  { symbol: "FTNT", name: "Fortinet", kind: "stock", region: "US" },
  { symbol: "SNOW", name: "Snowflake", kind: "stock", region: "US" },
  { symbol: "NET", name: "Cloudflare", kind: "stock", region: "US" },
  { symbol: "MDB", name: "MongoDB", kind: "stock", region: "US" },
  { symbol: "DASH", name: "DoorDash", kind: "stock", region: "US" },
  { symbol: "SPOT", name: "Spotify", kind: "stock", region: "US" },
  { symbol: "TTD", name: "The Trade Desk", kind: "stock", region: "US" },
  { symbol: "ROKU", name: "Roku", kind: "stock", region: "US" },
  { symbol: "COF", name: "Capital One", kind: "stock", region: "US" },
  { symbol: "USB", name: "U.S. Bancorp", kind: "stock", region: "US" },
  { symbol: "PNC", name: "PNC Financial", kind: "stock", region: "US" },
  { symbol: "TFC", name: "Truist", kind: "stock", region: "US" },
  { symbol: "BK", name: "Bank of New York Mellon", kind: "stock", region: "US" },
  { symbol: "STT", name: "State Street", kind: "stock", region: "US" },
  { symbol: "MET", name: "MetLife", kind: "stock", region: "US" },
  { symbol: "PRU", name: "Prudential", kind: "stock", region: "US" },
  { symbol: "AIG", name: "American International Group", kind: "stock", region: "US" },
  { symbol: "ALL", name: "Allstate", kind: "stock", region: "US" },
  { symbol: "TRV", name: "Travelers", kind: "stock", region: "US" },
  { symbol: "AJG", name: "Arthur J. Gallagher", kind: "stock", region: "US" },
  { symbol: "PH", name: "Parker-Hannifin", kind: "stock", region: "US" },
  { symbol: "EMR", name: "Emerson Electric", kind: "stock", region: "US" },
  { symbol: "ETN", name: "Eaton", kind: "stock", region: "US" },
  { symbol: "ITW", name: "Illinois Tool Works", kind: "stock", region: "US" },
  { symbol: "ROK", name: "Rockwell Automation", kind: "stock", region: "US" },
  { symbol: "CMI", name: "Cummins", kind: "stock", region: "US" },
  { symbol: "PCAR", name: "PACCAR", kind: "stock", region: "US" },
  { symbol: "URI", name: "United Rentals", kind: "stock", region: "US" },
  { symbol: "FAST", name: "Fastenal", kind: "stock", region: "US" },
  { symbol: "GWW", name: "W.W. Grainger", kind: "stock", region: "US" },
  { symbol: "CTAS", name: "Cintas", kind: "stock", region: "US" },
  { symbol: "PAYX", name: "Paychex", kind: "stock", region: "US" },
  { symbol: "ODFL", name: "Old Dominion Freight", kind: "stock", region: "US" },
  { symbol: "CSX", name: "CSX", kind: "stock", region: "US" },
  { symbol: "NSC", name: "Norfolk Southern", kind: "stock", region: "US" },
  { symbol: "DAL", name: "Delta Air Lines", kind: "stock", region: "US" },
  { symbol: "UAL", name: "United Airlines", kind: "stock", region: "US" },
  { symbol: "LUV", name: "Southwest Airlines", kind: "stock", region: "US" },
  { symbol: "MAR", name: "Marriott", kind: "stock", region: "US" },
  { symbol: "HLT", name: "Hilton", kind: "stock", region: "US" },
  { symbol: "YUM", name: "Yum! Brands", kind: "stock", region: "US" },
  { symbol: "CMG", name: "Chipotle", kind: "stock", region: "US" },
  { symbol: "DPZ", name: "Domino's Pizza", kind: "stock", region: "US" },
  { symbol: "ORLY", name: "O'Reilly Automotive", kind: "stock", region: "US" },
  { symbol: "AZO", name: "AutoZone", kind: "stock", region: "US" },
  { symbol: "ROST", name: "Ross Stores", kind: "stock", region: "US" },
  { symbol: "DG", name: "Dollar General", kind: "stock", region: "US" },
  { symbol: "DLTR", name: "Dollar Tree", kind: "stock", region: "US" },
  { symbol: "KR", name: "Kroger", kind: "stock", region: "US" },
  { symbol: "SYY", name: "Sysco", kind: "stock", region: "US" },
  { symbol: "ADM", name: "Archer-Daniels-Midland", kind: "stock", region: "US" },
  { symbol: "BG", name: "Bunge", kind: "stock", region: "US" },
  { symbol: "K", name: "Kellanova", kind: "stock", region: "US" },
  { symbol: "HSY", name: "Hershey", kind: "stock", region: "US" },
  { symbol: "MKC", name: "McCormick", kind: "stock", region: "US" },
  { symbol: "STZ", name: "Constellation Brands", kind: "stock", region: "US" },
  { symbol: "BF-B", name: "Brown-Forman", kind: "stock", region: "US" },
  { symbol: "EL", name: "Estée Lauder", kind: "stock", region: "US" },
  { symbol: "CHTR", name: "Charter Communications", kind: "stock", region: "US" },
  { symbol: "EA", name: "Electronic Arts", kind: "stock", region: "US" },
  { symbol: "TTWO", name: "Take-Two Interactive", kind: "stock", region: "US" },
  { symbol: "WBD", name: "Warner Bros. Discovery", kind: "stock", region: "US" },
  { symbol: "FOXA", name: "Fox A", kind: "stock", region: "US" },
  { symbol: "NWS", name: "News Corp", kind: "stock", region: "US" },
  { symbol: "MTCH", name: "Match Group", kind: "stock", region: "US" },
  { symbol: "LYV", name: "Live Nation", kind: "stock", region: "US" },
  { symbol: "ACN", name: "Accenture", kind: "stock", region: "US" },
  { symbol: "A", name: "Agilent Technologies", kind: "stock", region: "US" },
  { symbol: "ALGN", name: "Align Technology", kind: "stock", region: "US" },
  { symbol: "ANET", name: "Arista Networks", kind: "stock", region: "US" },
  { symbol: "AON", name: "Aon", kind: "stock", region: "US" },
  { symbol: "APH", name: "Amphenol", kind: "stock", region: "US" },
  { symbol: "APTV", name: "Aptiv", kind: "stock", region: "US" },
  { symbol: "ARE", name: "Alexandria Real Estate", kind: "stock", region: "US" },
  { symbol: "ATO", name: "Atmos Energy", kind: "stock", region: "US" },
  { symbol: "AVB", name: "AvalonBay Communities", kind: "stock", region: "US" },
  { symbol: "AWK", name: "American Water Works", kind: "stock", region: "US" },
  { symbol: "BALL", name: "Ball Corporation", kind: "stock", region: "US" },
  { symbol: "BDX", name: "Becton Dickinson", kind: "stock", region: "US" },
  { symbol: "BIIB", name: "Biogen", kind: "stock", region: "US" },
  { symbol: "BKNG", name: "Booking Holdings", kind: "stock", region: "US" },
  { symbol: "BKR", name: "Baker Hughes", kind: "stock", region: "US" },
  { symbol: "BR", name: "Broadridge Financial", kind: "stock", region: "US" },
  { symbol: "BRO", name: "Brown & Brown", kind: "stock", region: "US" },
  { symbol: "BSX", name: "Boston Scientific", kind: "stock", region: "US" },
  { symbol: "BX", name: "Blackstone", kind: "stock", region: "US" },
  { symbol: "CBOE", name: "Cboe Global Markets", kind: "stock", region: "US" },
  { symbol: "CDW", name: "CDW Corporation", kind: "stock", region: "US" },
  { symbol: "CEG", name: "Constellation Energy", kind: "stock", region: "US" },
  { symbol: "CF", name: "CF Industries", kind: "stock", region: "US" },
  { symbol: "CHD", name: "Church & Dwight", kind: "stock", region: "US" },
  { symbol: "CNC", name: "Centene", kind: "stock", region: "US" },
  { symbol: "CNP", name: "CenterPoint Energy", kind: "stock", region: "US" },
  { symbol: "COO", name: "Cooper Companies", kind: "stock", region: "US" },
  { symbol: "CPB", name: "Campbell Soup", kind: "stock", region: "US" },
  { symbol: "CPRT", name: "Copart", kind: "stock", region: "US" },
  { symbol: "CRL", name: "Charles River Laboratories", kind: "stock", region: "US" },
  { symbol: "CTRA", name: "Coterra Energy", kind: "stock", region: "US" },
  { symbol: "CTSH", name: "Cognizant", kind: "stock", region: "US" },
  { symbol: "CTVA", name: "Corteva", kind: "stock", region: "US" },
  { symbol: "D", name: "Dominion Energy", kind: "stock", region: "US" },
  { symbol: "DD", name: "DuPont", kind: "stock", region: "US" },
  { symbol: "DFS", name: "Discover Financial", kind: "stock", region: "US" },
  { symbol: "DGX", name: "Quest Diagnostics", kind: "stock", region: "US" },
  { symbol: "DHI", name: "D.R. Horton", kind: "stock", region: "US" },
  { symbol: "DTE", name: "DTE Energy", kind: "stock", region: "US" },
  { symbol: "DVN", name: "Devon Energy", kind: "stock", region: "US" },
  { symbol: "DXCM", name: "DexCom", kind: "stock", region: "US" },
  { symbol: "ECL", name: "Ecolab", kind: "stock", region: "US" },
  { symbol: "ED", name: "Consolidated Edison", kind: "stock", region: "US" },
  { symbol: "EFX", name: "Equifax", kind: "stock", region: "US" },
  { symbol: "EIX", name: "Edison International", kind: "stock", region: "US" },
  { symbol: "EQR", name: "Equity Residential", kind: "stock", region: "US" },
  { symbol: "EQT", name: "EQT Corporation", kind: "stock", region: "US" },
  { symbol: "ES", name: "Eversource Energy", kind: "stock", region: "US" },
  { symbol: "ESS", name: "Essex Property", kind: "stock", region: "US" },
  { symbol: "EXC", name: "Exelon", kind: "stock", region: "US" },
  { symbol: "EXPD", name: "Expeditors International", kind: "stock", region: "US" },
  { symbol: "EXPE", name: "Expedia", kind: "stock", region: "US" },
  { symbol: "EXR", name: "Extra Space Storage", kind: "stock", region: "US" },
  { symbol: "FANG", name: "Diamondback Energy", kind: "stock", region: "US" },
  { symbol: "FITB", name: "Fifth Third Bancorp", kind: "stock", region: "US" },
  { symbol: "FMC", name: "FMC Corporation", kind: "stock", region: "US" },
  { symbol: "FOX", name: "Fox B", kind: "stock", region: "US" },
  { symbol: "FTV", name: "Fortive", kind: "stock", region: "US" },
  { symbol: "GLW", name: "Corning", kind: "stock", region: "US" },
  { symbol: "HAL", name: "Halliburton", kind: "stock", region: "US" },
  { symbol: "HBAN", name: "Huntington Bancshares", kind: "stock", region: "US" },
  { symbol: "HCA", name: "HCA Healthcare", kind: "stock", region: "US" },
  { symbol: "HES", name: "Hess", kind: "stock", region: "US" },
  { symbol: "HIG", name: "Hartford Financial", kind: "stock", region: "US" },
  { symbol: "HOLX", name: "Hologic", kind: "stock", region: "US" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", kind: "stock", region: "US" },
  { symbol: "HPQ", name: "HP Inc", kind: "stock", region: "US" },
  { symbol: "HRL", name: "Hormel Foods", kind: "stock", region: "US" },
  { symbol: "HSIC", name: "Henry Schein", kind: "stock", region: "US" },
  { symbol: "HST", name: "Host Hotels", kind: "stock", region: "US" },
  { symbol: "HUM", name: "Humana", kind: "stock", region: "US" },
  { symbol: "HWM", name: "Howmet Aerospace", kind: "stock", region: "US" },
  { symbol: "IDXX", name: "IDEXX Laboratories", kind: "stock", region: "US" },
  { symbol: "IEX", name: "IDEX Corporation", kind: "stock", region: "US" },
  { symbol: "IFF", name: "International Flavors", kind: "stock", region: "US" },
  { symbol: "INCY", name: "Incyte", kind: "stock", region: "US" },
  { symbol: "INVH", name: "Invitation Homes", kind: "stock", region: "US" },
  { symbol: "IP", name: "International Paper", kind: "stock", region: "US" },
  { symbol: "IPG", name: "Interpublic Group", kind: "stock", region: "US" },
  { symbol: "IQV", name: "IQVIA", kind: "stock", region: "US" },
  { symbol: "IR", name: "Ingersoll Rand", kind: "stock", region: "US" },
  { symbol: "IRM", name: "Iron Mountain", kind: "stock", region: "US" },
  { symbol: "JBHT", name: "J.B. Hunt", kind: "stock", region: "US" },
  { symbol: "JCI", name: "Johnson Controls", kind: "stock", region: "US" },
  { symbol: "JKHY", name: "Jack Henry", kind: "stock", region: "US" },
  { symbol: "JNPR", name: "Juniper Networks", kind: "stock", region: "US" },
  { symbol: "KEY", name: "KeyCorp", kind: "stock", region: "US" },
  { symbol: "KEYS", name: "Keysight Technologies", kind: "stock", region: "US" },
  { symbol: "KHC", name: "Kraft Heinz", kind: "stock", region: "US" },
  { symbol: "KMI", name: "Kinder Morgan", kind: "stock", region: "US" },
  { symbol: "LEN", name: "Lennar", kind: "stock", region: "US" },
  { symbol: "LH", name: "Labcorp", kind: "stock", region: "US" },
  { symbol: "LHX", name: "L3Harris", kind: "stock", region: "US" },
  { symbol: "LDOS", name: "Leidos", kind: "stock", region: "US" },
  { symbol: "LULU", name: "Lululemon", kind: "stock", region: "US" },
  { symbol: "LVS", name: "Las Vegas Sands", kind: "stock", region: "US" },
  { symbol: "LYB", name: "LyondellBasell", kind: "stock", region: "US" },
  { symbol: "MAA", name: "Mid-America Apartment", kind: "stock", region: "US" },
  { symbol: "MCHP", name: "Microchip Technology", kind: "stock", region: "US" },
  { symbol: "MCK", name: "McKesson", kind: "stock", region: "US" },
  { symbol: "MCO", name: "Moody's", kind: "stock", region: "US" },
  { symbol: "MKTX", name: "MarketAxess", kind: "stock", region: "US" },
  { symbol: "MLM", name: "Martin Marietta", kind: "stock", region: "US" },
  { symbol: "MNST", name: "Monster Beverage", kind: "stock", region: "US" },
  { symbol: "MOH", name: "Molina Healthcare", kind: "stock", region: "US" },
  { symbol: "MOS", name: "Mosaic", kind: "stock", region: "US" },
  { symbol: "MPC", name: "Marathon Petroleum", kind: "stock", region: "US" },
  { symbol: "MPWR", name: "Monolithic Power", kind: "stock", region: "US" },
  { symbol: "MRNA", name: "Moderna", kind: "stock", region: "US" },
  { symbol: "MSCI", name: "MSCI Inc", kind: "stock", region: "US" },
  { symbol: "MSI", name: "Motorola Solutions", kind: "stock", region: "US" },
  { symbol: "MTB", name: "M&T Bank", kind: "stock", region: "US" },
  { symbol: "NDAQ", name: "Nasdaq Inc", kind: "stock", region: "US" },
  { symbol: "NDSN", name: "Nordson", kind: "stock", region: "US" },
  { symbol: "NTRS", name: "Northern Trust", kind: "stock", region: "US" },
  { symbol: "NUE", name: "Nucor", kind: "stock", region: "US" },
  { symbol: "NVR", name: "NVR Inc", kind: "stock", region: "US" },
  { symbol: "NXPI", name: "NXP Semiconductors", kind: "stock", region: "US" },
  { symbol: "OKE", name: "ONEOK", kind: "stock", region: "US" },
  { symbol: "ON", name: "ON Semiconductor", kind: "stock", region: "US" },
  { symbol: "OTIS", name: "Otis Worldwide", kind: "stock", region: "US" },
  { symbol: "PAYC", name: "Paycom", kind: "stock", region: "US" },
  { symbol: "PCG", name: "PG&E", kind: "stock", region: "US" },
  { symbol: "PEG", name: "Public Service Enterprise", kind: "stock", region: "US" },
  { symbol: "PFG", name: "Principal Financial", kind: "stock", region: "US" },
  { symbol: "PPL", name: "PPL Corporation", kind: "stock", region: "US" },
  { symbol: "PSA", name: "Public Storage", kind: "stock", region: "US" },
  { symbol: "PSX", name: "Phillips 66", kind: "stock", region: "US" },
  { symbol: "PTC", name: "PTC Inc", kind: "stock", region: "US" },
  { symbol: "PWR", name: "Quanta Services", kind: "stock", region: "US" },
  { symbol: "REGN", name: "Regeneron", kind: "stock", region: "US" },
  { symbol: "RF", name: "Regions Financial", kind: "stock", region: "US" },
  { symbol: "RJF", name: "Raymond James", kind: "stock", region: "US" },
  { symbol: "RMD", name: "ResMed", kind: "stock", region: "US" },
  { symbol: "ROP", name: "Roper Technologies", kind: "stock", region: "US" },
  { symbol: "RSG", name: "Republic Services", kind: "stock", region: "US" },
  { symbol: "SBAC", name: "SBA Communications", kind: "stock", region: "US" },
  { symbol: "SJM", name: "J.M. Smucker", kind: "stock", region: "US" },
  { symbol: "SNA", name: "Snap-on", kind: "stock", region: "US" },
  { symbol: "SRE", name: "Sempra", kind: "stock", region: "US" },
  { symbol: "STE", name: "STERIS", kind: "stock", region: "US" },
  { symbol: "STLD", name: "Steel Dynamics", kind: "stock", region: "US" },
  { symbol: "STX", name: "Seagate Technology", kind: "stock", region: "US" },
  { symbol: "SWK", name: "Stanley Black & Decker", kind: "stock", region: "US" },
  { symbol: "SYF", name: "Synchrony Financial", kind: "stock", region: "US" },
  { symbol: "TDG", name: "TransDigm", kind: "stock", region: "US" },
  { symbol: "TDY", name: "Teledyne", kind: "stock", region: "US" },
  { symbol: "TEL", name: "TE Connectivity", kind: "stock", region: "US" },
  { symbol: "TER", name: "Teradyne", kind: "stock", region: "US" },
  { symbol: "TFX", name: "Teleflex", kind: "stock", region: "US" },
  { symbol: "TROW", name: "T. Rowe Price", kind: "stock", region: "US" },
  { symbol: "TSCO", name: "Tractor Supply", kind: "stock", region: "US" },
  { symbol: "TT", name: "Trane Technologies", kind: "stock", region: "US" },
  { symbol: "TXT", name: "Textron", kind: "stock", region: "US" },
  { symbol: "TYL", name: "Tyler Technologies", kind: "stock", region: "US" },
  { symbol: "ULTA", name: "Ulta Beauty", kind: "stock", region: "US" },
  { symbol: "VLO", name: "Valero Energy", kind: "stock", region: "US" },
  { symbol: "VMC", name: "Vulcan Materials", kind: "stock", region: "US" },
  { symbol: "VRSK", name: "Verisk Analytics", kind: "stock", region: "US" },
  { symbol: "VRSN", name: "Verisign", kind: "stock", region: "US" },
  { symbol: "VTR", name: "Ventas", kind: "stock", region: "US" },
  { symbol: "VTRS", name: "Viatris", kind: "stock", region: "US" },
  { symbol: "WAB", name: "Wabtec", kind: "stock", region: "US" },
  { symbol: "WAT", name: "Waters", kind: "stock", region: "US" },
  { symbol: "WEC", name: "WEC Energy", kind: "stock", region: "US" },
  { symbol: "WELL", name: "Welltower", kind: "stock", region: "US" },
  { symbol: "WST", name: "West Pharmaceutical", kind: "stock", region: "US" },
  { symbol: "WTW", name: "Willis Towers Watson", kind: "stock", region: "US" },
  { symbol: "WY", name: "Weyerhaeuser", kind: "stock", region: "US" },
  { symbol: "WYNN", name: "Wynn Resorts", kind: "stock", region: "US" },
  { symbol: "XEL", name: "Xcel Energy", kind: "stock", region: "US" },
  { symbol: "XYL", name: "Xylem", kind: "stock", region: "US" },
  { symbol: "ZBH", name: "Zimmer Biomet", kind: "stock", region: "US" },
  { symbol: "ZBRA", name: "Zebra Technologies", kind: "stock", region: "US" },
  { symbol: "ZTS", name: "Zoetis", kind: "stock", region: "US" },
  { symbol: "CAG", name: "Conagra Brands", kind: "stock", region: "US" },
  { symbol: "MPW", name: "Medical Properties Trust", kind: "stock", region: "US" },
  { symbol: "VICI", name: "VICI Properties", kind: "stock", region: "US" },
  { symbol: "PBR-A", name: "Petrobras preferred ADR", kind: "stock", region: "LATAM" },
  { symbol: "IBE.MC", name: "Iberdrola", kind: "stock", region: "EU" },
];

export const SIC_ETFS: SicItem[] = [
  { symbol: "SPY", name: "SPDR S&P 500", kind: "etf", region: "US" },
  { symbol: "IVV", name: "iShares Core S&P 500", kind: "etf", region: "US" },
  { symbol: "VOO", name: "Vanguard S&P 500", kind: "etf", region: "US" },
  { symbol: "QQQ", name: "Invesco QQQ", kind: "etf", region: "US" },
  { symbol: "VTI", name: "Vanguard Total Stock Market", kind: "etf", region: "US" },
  { symbol: "ITOT", name: "iShares Core S&P Total US", kind: "etf", region: "US" },
  { symbol: "IWM", name: "iShares Russell 2000", kind: "etf", region: "US" },
  { symbol: "DIA", name: "SPDR Dow Jones", kind: "etf", region: "US" },
  { symbol: "MDY", name: "SPDR S&P MidCap 400", kind: "etf", region: "US" },
  { symbol: "SCHD", name: "Schwab US Dividend Equity", kind: "etf", region: "US" },
  { symbol: "VIG", name: "Vanguard Dividend Appreciation", kind: "etf", region: "US" },
  { symbol: "VYM", name: "Vanguard High Dividend Yield", kind: "etf", region: "US" },
  { symbol: "DVY", name: "iShares Select Dividend", kind: "etf", region: "US" },
  { symbol: "SDY", name: "SPDR S&P Dividend", kind: "etf", region: "US" },
  { symbol: "NOBL", name: "ProShares S&P 500 Aristocrats", kind: "etf", region: "US" },
  { symbol: "DGRO", name: "iShares Core Dividend Growth", kind: "etf", region: "US" },
  { symbol: "HDV", name: "iShares Core High Dividend", kind: "etf", region: "US" },
  { symbol: "SPYD", name: "SPDR Portfolio S&P 500 High Div", kind: "etf", region: "US" },
  { symbol: "JEPI", name: "JPMorgan Equity Premium Income", kind: "etf", region: "US" },
  { symbol: "JEPQ", name: "JPMorgan Nasdaq Premium Income", kind: "etf", region: "US" },
  { symbol: "QYLD", name: "Global X Nasdaq 100 Covered Call", kind: "etf", region: "US" },
  { symbol: "DIV", name: "Global X SuperDividend", kind: "etf", region: "US" },
  { symbol: "SCHG", name: "Schwab US Large-Cap Growth", kind: "etf", region: "US" },
  { symbol: "SCHV", name: "Schwab US Large-Cap Value", kind: "etf", region: "US" },
  { symbol: "VUG", name: "Vanguard Growth", kind: "etf", region: "US" },
  { symbol: "VTV", name: "Vanguard Value", kind: "etf", region: "US" },
  { symbol: "VO", name: "Vanguard Mid-Cap", kind: "etf", region: "US" },
  { symbol: "VB", name: "Vanguard Small-Cap", kind: "etf", region: "US" },
  { symbol: "XLK", name: "Technology Select Sector", kind: "etf", region: "US" },
  { symbol: "XLF", name: "Financial Select Sector", kind: "etf", region: "US" },
  { symbol: "XLE", name: "Energy Select Sector", kind: "etf", region: "US" },
  { symbol: "XLV", name: "Health Care Select Sector", kind: "etf", region: "US" },
  { symbol: "XLI", name: "Industrial Select Sector", kind: "etf", region: "US" },
  { symbol: "XLP", name: "Consumer Staples Select", kind: "etf", region: "US" },
  { symbol: "XLY", name: "Consumer Discretionary Select", kind: "etf", region: "US" },
  { symbol: "XLU", name: "Utilities Select Sector", kind: "etf", region: "US" },
  { symbol: "XLB", name: "Materials Select Sector", kind: "etf", region: "US" },
  { symbol: "XLRE", name: "Real Estate Select Sector", kind: "etf", region: "US" },
  { symbol: "XLC", name: "Communication Services Select", kind: "etf", region: "US" },
  { symbol: "SMH", name: "VanEck Semiconductor", kind: "etf", region: "US" },
  { symbol: "SOXX", name: "iShares Semiconductor", kind: "etf", region: "US" },
  { symbol: "ARKK", name: "ARK Innovation", kind: "etf", region: "US" },
  { symbol: "VNQ", name: "Vanguard Real Estate", kind: "etf", region: "US" },
  { symbol: "SCHH", name: "Schwab US REIT", kind: "etf", region: "US" },
  { symbol: "GLD", name: "SPDR Gold Shares", kind: "etf", region: "GLOBAL" },
  { symbol: "IAU", name: "iShares Gold Trust", kind: "etf", region: "GLOBAL" },
  { symbol: "SLV", name: "iShares Silver Trust", kind: "etf", region: "GLOBAL" },
  { symbol: "USO", name: "United States Oil Fund", kind: "etf", region: "GLOBAL" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury", kind: "etf", region: "US" },
  { symbol: "IEF", name: "iShares 7-10 Year Treasury", kind: "etf", region: "US" },
  { symbol: "SHY", name: "iShares 1-3 Year Treasury", kind: "etf", region: "US" },
  { symbol: "SHV", name: "iShares Short Treasury", kind: "etf", region: "US" },
  { symbol: "BIL", name: "SPDR Bloomberg 1-3 Month T-Bill", kind: "etf", region: "US" },
  { symbol: "BND", name: "Vanguard Total Bond Market", kind: "etf", region: "US" },
  { symbol: "AGG", name: "iShares Core US Aggregate Bond", kind: "etf", region: "US" },
  { symbol: "LQD", name: "iShares iBoxx $ Inv Grade Corp", kind: "etf", region: "US" },
  { symbol: "HYG", name: "iShares iBoxx $ High Yield Corp", kind: "etf", region: "US" },
  { symbol: "JNK", name: "SPDR Bloomberg High Yield Bond", kind: "etf", region: "US" },
  { symbol: "VCIT", name: "Vanguard Int-Term Corporate Bond", kind: "etf", region: "US" },
  { symbol: "VCSH", name: "Vanguard Short-Term Corporate", kind: "etf", region: "US" },
  { symbol: "VCLT", name: "Vanguard Long-Term Corporate", kind: "etf", region: "US" },
  { symbol: "TIP", name: "iShares TIPS Bond", kind: "etf", region: "US" },
  { symbol: "ACWI", name: "iShares MSCI ACWI", kind: "etf", region: "GLOBAL" },
  { symbol: "VT", name: "Vanguard Total World Stock", kind: "etf", region: "GLOBAL" },
  { symbol: "VXUS", name: "Vanguard Total International Stock", kind: "etf", region: "GLOBAL" },
  { symbol: "IXUS", name: "iShares Core MSCI Total Intl", kind: "etf", region: "GLOBAL" },
  { symbol: "EFA", name: "iShares MSCI EAFE", kind: "etf", region: "EU" },
  { symbol: "IEFA", name: "iShares Core MSCI EAFE", kind: "etf", region: "EU" },
  { symbol: "VEA", name: "Vanguard FTSE Developed Markets", kind: "etf", region: "EU" },
  { symbol: "EEM", name: "iShares MSCI Emerging Markets", kind: "etf", region: "GLOBAL" },
  { symbol: "IEMG", name: "iShares Core MSCI Emerging Mkts", kind: "etf", region: "GLOBAL" },
  { symbol: "VWO", name: "Vanguard FTSE Emerging Markets", kind: "etf", region: "GLOBAL" },
  { symbol: "EMXC", name: "iShares MSCI EM ex China", kind: "etf", region: "GLOBAL" },
  { symbol: "EWZ", name: "iShares MSCI Brazil", kind: "etf", region: "LATAM" },
  { symbol: "ILF", name: "iShares Latin America 40", kind: "etf", region: "LATAM" },
  { symbol: "EWW", name: "iShares MSCI Mexico", kind: "etf", region: "LATAM" },
  { symbol: "EWJ", name: "iShares MSCI Japan", kind: "etf", region: "ASIA" },
  { symbol: "FXI", name: "iShares China Large-Cap", kind: "etf", region: "ASIA" },
  { symbol: "MCHI", name: "iShares MSCI China", kind: "etf", region: "ASIA" },
  { symbol: "EWY", name: "iShares MSCI South Korea", kind: "etf", region: "ASIA" },
  { symbol: "EWT", name: "iShares MSCI Taiwan", kind: "etf", region: "ASIA" },
  { symbol: "INDA", name: "iShares MSCI India", kind: "etf", region: "ASIA" },
  { symbol: "AAXJ", name: "iShares MSCI All Country Asia ex JP", kind: "etf", region: "ASIA" },
  { symbol: "EWG", name: "iShares MSCI Germany", kind: "etf", region: "EU" },
  { symbol: "EWU", name: "iShares MSCI United Kingdom", kind: "etf", region: "EU" },
  { symbol: "EWQ", name: "iShares MSCI France", kind: "etf", region: "EU" },
  { symbol: "EWP", name: "iShares MSCI Spain", kind: "etf", region: "EU" },
  { symbol: "EWC", name: "iShares MSCI Canada", kind: "etf", region: "US" },
  { symbol: "EWA", name: "iShares MSCI Australia", kind: "etf", region: "ASIA" },
  { symbol: "EZU", name: "iShares MSCI Eurozone", kind: "etf", region: "EU" },
  { symbol: "FEZ", name: "SPDR EURO STOXX 50", kind: "etf", region: "EU" },
  { symbol: "VGK", name: "Vanguard FTSE Europe", kind: "etf", region: "EU" },
  { symbol: "VIGI", name: "Vanguard Intl Dividend Appreciation", kind: "etf", region: "GLOBAL" },
  { symbol: "VYMI", name: "Vanguard Intl High Dividend Yield", kind: "etf", region: "GLOBAL" },
  { symbol: "IDV", name: "iShares International Select Div", kind: "etf", region: "GLOBAL" },
{ symbol: "SPYG", name: "SPDR Portfolio S&P 500 Growth", kind: "etf", region: "US" },
  { symbol: "SPYV", name: "SPDR Portfolio S&P 500 Value", kind: "etf", region: "US" },
  { symbol: "IJH", name: "iShares Core S&P Mid-Cap", kind: "etf", region: "US" },
  { symbol: "IJR", name: "iShares Core S&P Small-Cap", kind: "etf", region: "US" },
  { symbol: "MGK", name: "Vanguard Mega Cap Growth", kind: "etf", region: "US" },
  { symbol: "MGV", name: "Vanguard Mega Cap Value", kind: "etf", region: "US" },
  { symbol: "QUAL", name: "iShares MSCI USA Quality Factor", kind: "etf", region: "US" },
  { symbol: "VLUE", name: "iShares MSCI USA Value Factor", kind: "etf", region: "US" },
  { symbol: "MTUM", name: "iShares MSCI USA Momentum Factor", kind: "etf", region: "US" },
  { symbol: "USMV", name: "iShares MSCI USA Min Vol", kind: "etf", region: "US" },
  { symbol: "SIZE", name: "iShares MSCI USA Size Factor", kind: "etf", region: "US" },
  { symbol: "RSP", name: "Invesco S&P 500 Equal Weight", kind: "etf", region: "US" },
  { symbol: "SPL", name: "SPDR Portfolio S&P 500", kind: "etf", region: "US" },
  { symbol: "SPLG", name: "SPDR Portfolio S&P 500", kind: "etf", region: "US" },
  { symbol: "IVW", name: "iShares S&P 500 Growth", kind: "etf", region: "US" },
  { symbol: "IVE", name: "iShares S&P 500 Value", kind: "etf", region: "US" },
  { symbol: "IWD", name: "iShares Russell 1000 Value", kind: "etf", region: "US" },
  { symbol: "IWF", name: "iShares Russell 1000 Growth", kind: "etf", region: "US" },
  { symbol: "IWB", name: "iShares Russell 1000", kind: "etf", region: "US" },
  { symbol: "IWV", name: "iShares Russell 3000", kind: "etf", region: "US" },
  { symbol: "OEF", name: "iShares S&P 100", kind: "etf", region: "US" },
  { symbol: "IGV", name: "iShares Expanded Tech-Software", kind: "etf", region: "US" },
  { symbol: "SKYY", name: "First Trust Cloud Computing", kind: "etf", region: "US" },
  { symbol: "WCLD", name: "WisdomTree Cloud Computing", kind: "etf", region: "US" },
  { symbol: "FINX", name: "Global X FinTech", kind: "etf", region: "US" },
  { symbol: "ICLN", name: "iShares Global Clean Energy", kind: "etf", region: "US" },
  { symbol: "TAN", name: "Invesco Solar", kind: "etf", region: "US" },
  { symbol: "LIT", name: "Global X Lithium & Battery Tech", kind: "etf", region: "US" },
  { symbol: "REMX", name: "VanEck Rare Earth/Strategic Metals", kind: "etf", region: "US" },
  { symbol: "GDX", name: "VanEck Gold Miners", kind: "etf", region: "US" },
  { symbol: "GDXJ", name: "VanEck Junior Gold Miners", kind: "etf", region: "US" },
  { symbol: "XOP", name: "SPDR S&P Oil & Gas Exploration", kind: "etf", region: "US" },
  { symbol: "OIH", name: "VanEck Oil Services", kind: "etf", region: "US" },
  { symbol: "XBI", name: "SPDR S&P Biotech", kind: "etf", region: "US" },
  { symbol: "IBB", name: "iShares Biotechnology", kind: "etf", region: "US" },
  { symbol: "KWEB", name: "KraneShares CSI China Internet", kind: "etf", region: "ASIA" },
  { symbol: "ASHR", name: "Xtrackers Harvest CSI 300 China", kind: "etf", region: "ASIA" },
  { symbol: "EWH", name: "iShares MSCI Hong Kong", kind: "etf", region: "ASIA" },
  { symbol: "SGOV", name: "iShares 0-3 Month Treasury", kind: "etf", region: "US" },
  { symbol: "IEI", name: "iShares 3-7 Year Treasury", kind: "etf", region: "US" },
  { symbol: "GOVT", name: "iShares US Treasury Bond", kind: "etf", region: "US" },
  { symbol: "VGSH", name: "Vanguard Short-Term Treasury", kind: "etf", region: "US" },
  { symbol: "VGIT", name: "Vanguard Intermediate-Term Treasury", kind: "etf", region: "US" },
  { symbol: "VGLT", name: "Vanguard Long-Term Treasury", kind: "etf", region: "US" },
  { symbol: "SJNK", name: "SPDR Bloomberg Short Term High Yield", kind: "etf", region: "US" },
  { symbol: "BKLN", name: "Invesco Senior Loan", kind: "etf", region: "US" },
  { symbol: "SRLN", name: "SPDR Blackstone Senior Loan", kind: "etf", region: "US" },
  { symbol: "MUB", name: "iShares National Muni Bond", kind: "etf", region: "US" },
  { symbol: "VTEB", name: "Vanguard Tax-Exempt Bond", kind: "etf", region: "US" },
  { symbol: "EMB", name: "iShares J.P. Morgan USD EM Bond", kind: "etf", region: "US" },
  { symbol: "PCY", name: "Invesco Emerging Markets Sovereign", kind: "etf", region: "US" },
  { symbol: "BWX", name: "SPDR Bloomberg International Treasury", kind: "etf", region: "US" },
  { symbol: "WIP", name: "SPDR FTSE International Government Inflation-Protected", kind: "etf", region: "US" },
  { symbol: "SCHP", name: "Schwab US TIPS", kind: "etf", region: "US" },
  { symbol: "VTIP", name: "Vanguard Short-Term Inflation-Protected", kind: "etf", region: "US" },
  { symbol: "CWB", name: "SPDR Bloomberg Convertible Securities", kind: "etf", region: "US" },
  { symbol: "PFF", name: "iShares Preferred and Income Securities", kind: "etf", region: "US" },
  { symbol: "PGX", name: "Invesco Preferred", kind: "etf", region: "US" },
  { symbol: "SCHB", name: "Schwab US Broad Market", kind: "etf", region: "US" },
  { symbol: "SCHX", name: "Schwab US Large-Cap", kind: "etf", region: "US" },
  { symbol: "SCHA", name: "Schwab US Small-Cap", kind: "etf", region: "US" },
  { symbol: "SCHF", name: "Schwab International Equity", kind: "etf", region: "US" },
  { symbol: "SCHE", name: "Schwab Emerging Markets Equity", kind: "etf", region: "US" },
  { symbol: "IYR", name: "iShares US Real Estate", kind: "etf", region: "US" },
  { symbol: "XHB", name: "SPDR S&P Homebuilders", kind: "etf", region: "US" },
  { symbol: "ITB", name: "iShares US Home Construction", kind: "etf", region: "US" },
  { symbol: "KRE", name: "SPDR S&P Regional Banking", kind: "etf", region: "US" },
  { symbol: "QTEC", name: "First Trust NASDAQ-100 Technology", kind: "etf", region: "US" },
  { symbol: "VGT", name: "Vanguard Information Technology", kind: "etf", region: "US" },
  { symbol: "VHT", name: "Vanguard Health Care", kind: "etf", region: "US" },
  { symbol: "VFH", name: "Vanguard Financials", kind: "etf", region: "US" },
  { symbol: "VIS", name: "Vanguard Industrials", kind: "etf", region: "US" },
  { symbol: "VDE", name: "Vanguard Energy", kind: "etf", region: "US" },
  { symbol: "VAW", name: "Vanguard Materials", kind: "etf", region: "US" },
  { symbol: "VDC", name: "Vanguard Consumer Staples", kind: "etf", region: "US" },
  { symbol: "VCR", name: "Vanguard Consumer Discretionary", kind: "etf", region: "US" },
  { symbol: "VOX", name: "Vanguard Communication Services", kind: "etf", region: "US" },
  { symbol: "VPU", name: "Vanguard Utilities", kind: "etf", region: "US" },
  { symbol: "DIVO", name: "Amplify CWP Enhanced Dividend Income", kind: "etf", region: "US" },
  { symbol: "XYLD", name: "Global X S&P 500 Covered Call", kind: "etf", region: "US" },
  { symbol: "RYLD", name: "Global X Russell 2000 Covered Call", kind: "etf", region: "US" },
  { symbol: "ALTY", name: "Global X Alternative Income ETF", kind: "etf", region: "US" },
  { symbol: "PFFD", name: "Global X U.S. Preferred ETF", kind: "etf", region: "US" },
  { symbol: "SRET", name: "Global X SuperDividend REIT ETF", kind: "etf", region: "US" },
  { symbol: "SPHD", name: "Invesco S&P 500 High Dividend Low Volatility ETF", kind: "etf", region: "US" },
  { symbol: "FDD", name: "First Trust STOXX European Select Dividend ETF", kind: "etf", region: "US" },
];

export const SIC_UCITS: SicItem[] = [
  { symbol: "CSPX", name: "iShares Core S&P 500 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "CSP1", name: "iShares Core S&P 500 UCITS (alt)", kind: "etf", region: "GLOBAL" },
  { symbol: "VUAA", name: "Vanguard S&P 500 UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VUSA", name: "Vanguard S&P 500 UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "VUSD", name: "Vanguard S&P 500 UCITS USD", kind: "etf", region: "GLOBAL" },
  { symbol: "SPYL", name: "SPDR S&P 500 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SPX5", name: "SPDR S&P 500 UCITS (alt)", kind: "etf", region: "GLOBAL" },
  { symbol: "SXR8", name: "iShares Core S&P 500 UCITS EUR", kind: "etf", region: "GLOBAL" },
  { symbol: "IUAA", name: "iShares S&P 500 UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IUSA", name: "iShares S&P 500 UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "EQQQ", name: "Invesco EQQQ NASDAQ-100 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "CNDX", name: "iShares NASDAQ 100 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXRV", name: "iShares NASDAQ 100 UCITS EUR", kind: "etf", region: "GLOBAL" },
  { symbol: "VUAG", name: "Vanguard S&P 500 UCITS GBP Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VWCE", name: "Vanguard FTSE All-World UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VWRA", name: "Vanguard FTSE All-World UCITS Acc USD", kind: "etf", region: "GLOBAL" },
  { symbol: "VWRD", name: "Vanguard FTSE All-World UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "VWRL", name: "Vanguard FTSE All-World UCITS Dist GBP", kind: "etf", region: "GLOBAL" },
  { symbol: "IWDA", name: "iShares Core MSCI World UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "SWDA", name: "iShares Core MSCI World UCITS Acc GBP", kind: "etf", region: "GLOBAL" },
  { symbol: "IWRD", name: "iShares MSCI World UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "EUNL", name: "iShares Core MSCI World UCITS EUR", kind: "etf", region: "GLOBAL" },
  { symbol: "SSAC", name: "iShares MSCI ACWI UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "ISAC", name: "iShares MSCI ACWI UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VWYG", name: "Vanguard FTSE Developed World UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VEVE", name: "Vanguard FTSE Developed World UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VEUR", name: "Vanguard FTSE Developed Europe UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VERX", name: "Vanguard FTSE Developed Europe UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VGEA", name: "Vanguard EUR Eurozone Gov Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VAGS", name: "Vanguard Global Aggregate Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VAGF", name: "Vanguard Global Aggregate Bond UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VDST", name: "Vanguard 0-1 Year US Treasury UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VUTY", name: "Vanguard USD Treasury Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VDCP", name: "Vanguard USD Corporate Bond UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "VDUC", name: "Vanguard USD Corporate 1-3 Year UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "VUCP", name: "Vanguard USD Corporate Bond UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "EIMI", name: "iShares Core MSCI EM IMI UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "EMIM", name: "iShares Core MSCI EM IMI UCITS Acc GBP", kind: "etf", region: "GLOBAL" },
  { symbol: "IEML", name: "iShares Core MSCI EM IMI UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IS3N", name: "iShares Core MSCI EM IMI UCITS EUR", kind: "etf", region: "GLOBAL" },
  { symbol: "MXUS", name: "Invesco MSCI USA UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SPXS", name: "Invesco S&P 500 UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "SPXP", name: "Invesco S&P 500 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "MEUD", name: "Lyxor Core STOXX Europe 600 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "EXSA", name: "iShares STOXX Europe 600 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXR1", name: "iShares Core EURO STOXX 50 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "EUE", name: "iShares EURO STOXX 50 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "C50", name: "Amundi EURO STOXX 50 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "MSE", name: "iShares Core MSCI Europe UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IMEU", name: "iShares Core MSCI Europe UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "CEU", name: "Amundi MSCI Europe UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "XMEU", name: "Xtrackers MSCI Europe UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "XMWD", name: "Xtrackers MSCI World UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "XWLD", name: "Xtrackers MSCI World UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "XDWD", name: "Xtrackers MSCI World UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "XDEW", name: "Xtrackers S&P 500 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "XSPX", name: "Xtrackers S&P 500 Equal Weight UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "XDER", name: "Xtrackers EURO STOXX 50 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "XDDX", name: "Xtrackers DAX UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "XDAX", name: "Xtrackers DAX UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "EXW1", name: "iShares Core DAX UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "DAXEX", name: "iShares DAX UCITS DE", kind: "etf", region: "GLOBAL" },
  { symbol: "ISF", name: "iShares Core FTSE 100 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VUKE", name: "Vanguard FTSE 100 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VUKG", name: "Vanguard FTSE 100 UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "HMWO", name: "HSBC MSCI World UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMWD", name: "HSBC MSCI World UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "HMEF", name: "HSBC MSCI Europe UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMUS", name: "HSBC MSCI USA UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMCH", name: "HSBC MSCI China UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMJP", name: "HSBC MSCI Japan UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IJPN", name: "iShares MSCI Japan UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IJPA", name: "iShares MSCI Japan UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "CSJP", name: "iShares MSCI Japan UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXJP", name: "iShares Core MSCI Japan IMI UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VJPN", name: "Vanguard FTSE Japan UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VAPX", name: "Vanguard FTSE Developed Asia Pacific UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VFEM", name: "Vanguard FTSE Emerging Markets UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VFEA", name: "Vanguard FTSE Emerging Markets UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IEEM", name: "iShares MSCI EM UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "IEMM", name: "iShares MSCI EM UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "EMMU", name: "iShares Core MSCI EM IMI UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "CSEM", name: "iShares MSCI EM UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "FXC", name: "iShares China Large Cap UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "ICHN", name: "iShares MSCI China UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "ICGA", name: "iShares MSCI China UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "CNYA", name: "iShares MSCI China A UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "CSNDX", name: "iShares NASDAQ 100 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "EQAC", name: "Invesco EQQQ NASDAQ-100 UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IUIT", name: "iShares S&P 500 Info Tech UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IUHC", name: "iShares S&P 500 Health Care UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IUFS", name: "iShares S&P 500 Financials UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IUES", name: "iShares S&P 500 Energy UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IUCS", name: "iShares S&P 500 Consumer Staples UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IUCD", name: "iShares S&P 500 Consumer Disc UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IUID", name: "iShares S&P 500 Industrials UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IUST", name: "iShares S&P 500 Utilities UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "QDVE", name: "iShares S&P 500 Info Tech UCITS EUR", kind: "etf", region: "GLOBAL" },
  { symbol: "QDVM", name: "iShares S&P 500 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SPYI", name: "SPDR S&P 500 UCITS EUR Hdg", kind: "etf", region: "GLOBAL" },
  { symbol: "SPY5", name: "SPDR S&P 500 UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SPYX", name: "SPDR S&P 500 UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "WLD", name: "SPDR MSCI World UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SWRD", name: "SPDR MSCI World UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "EMRD", name: "SPDR MSCI EM UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SPY4", name: "SPDR S&P 400 US Mid Cap UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "R2US", name: "SPDR Russell 2000 US Small Cap UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "WDSC", name: "SPDR MSCI World Small Cap UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "EMSD", name: "SPDR MSCI EM Small Cap UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "EMAD", name: "SPDR MSCI EM Asia UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLY", name: "SPDR S&P US Consumer Discretionary UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLP", name: "SPDR S&P US Consumer Staples UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLE", name: "SPDR S&P US Energy UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLF", name: "SPDR S&P US Financials UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLV", name: "SPDR S&P US Health Care UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLI", name: "SPDR S&P US Industrials UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLB", name: "SPDR S&P US Materials UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLU", name: "SPDR S&P US Utilities UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SXLG", name: "SPDR S&P US Technology UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "GLAG", name: "SPDR Bloomberg Global Aggregate Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SYBN", name: "SPDR Bloomberg 0-3 Treasury UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "TRET", name: "VanEck Global Real Estate UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SMGB", name: "VanEck Semiconductor UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "ESGB", name: "VanEck Sustainable World Equal Weight UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "TSWE", name: "VanEck Sustainable World UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "V3AA", name: "Vanguard ESG Global All Cap UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "V3AL", name: "Vanguard ESG Developed World All Cap UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VDNR", name: "Vanguard FTSE North America UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VNRT", name: "Vanguard FTSE North America UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VHVG", name: "Vanguard FTSE Developed Europe UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VJPA", name: "Vanguard FTSE Japan UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VAPA", name: "Vanguard FTSE Developed Asia Pacific UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "VAGP", name: "Vanguard Global Aggregate Bond UCITS GBP Hdg", kind: "etf", region: "GLOBAL" },
  { symbol: "VETA", name: "Vanguard EUR Eurozone Government Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VECP", name: "Vanguard EUR Corporate Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "VETY", name: "Vanguard EUR Eurozone Gov Bond UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IB01", name: "iShares $ Treasury Bond 0-1yr UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IBTA", name: "iShares $ Treasury Bond 1-3yr UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "CBU7", name: "iShares $ Treasury Bond 3-7yr UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "CBU0", name: "iShares $ Treasury Bond 7-10yr UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IDTP", name: "iShares $ TIPS UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "DTLA", name: "iShares $ Treasury Bond 20+yr UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IDTL", name: "iShares $ Treasury Bond 20+yr UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "LQDA", name: "iShares $ Corp Bond UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "LQDE", name: "iShares $ Corp Bond UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "IHYA", name: "iShares $ High Yield Corp Bond UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IHYU", name: "iShares $ High Yield Corp Bond UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "SDHA", name: "iShares $ Short Duration High Yield Corp Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SDIA", name: "iShares $ Short Duration Corp Bond UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "SDIG", name: "iShares $ Short Duration Corp Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "FLOA", name: "iShares $ Floating Rate Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "JPEA", name: "iShares J.P. Morgan $ EM Bond UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IEMB", name: "iShares J.P. Morgan $ EM Bond UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "EMGA", name: "iShares J.P. Morgan EM Local Govt Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "EUNA", name: "iShares Core Global Aggregate Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "AGGH", name: "iShares Core Global Aggregate Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IEAG", name: "iShares Core Global Aggregate Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IGLA", name: "iShares Global Govt Bond UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IGLS", name: "iShares Global Govt Bond UCITS Dist", kind: "etf", region: "GLOBAL" },
  { symbol: "SUAS", name: "iShares MSCI USA SRI UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "SUWS", name: "iShares MSCI World SRI UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "2B7K", name: "iShares MSCI World SRI UCITS EUR Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IUSN", name: "iShares MSCI World Small Cap UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "WSML", name: "iShares MSCI World Small Cap UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "MVOL", name: "iShares Edge MSCI World Min Vol UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "MVUS", name: "iShares Edge S&P 500 Min Vol UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "SPMV", name: "iShares Edge S&P 500 Min Vol UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IWMO", name: "iShares Edge MSCI World Momentum UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IWQU", name: "iShares Edge MSCI World Quality UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IWVL", name: "iShares Edge MSCI World Value UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "RBOT", name: "iShares Automation & Robotics UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "LOCK", name: "iShares Digital Security UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HEAL", name: "iShares Healthcare Innovation UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "ECAR", name: "iShares Electric Vehicles UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "INRG", name: "iShares Global Clean Energy UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IAUP", name: "iShares Gold Producers UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "WTEA", name: "WisdomTree Enhanced Commodity UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "CMOD", name: "Invesco Bloomberg Commodity UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "AIGI", name: "iShares Diversified Commodity Swap UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "EIMU", name: "iShares Core MSCI EM IMI UCITS USD", kind: "etf", region: "GLOBAL" },
  { symbol: "SAWD", name: "iShares MSCI World UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "HWRD", name: "HSBC MSCI World UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "HMEU", name: "HSBC MSCI Europe UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMAD", name: "HSBC MSCI AC Asia Pacific ex Japan UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMXJ", name: "HSBC MSCI Pacific ex Japan UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMSE", name: "HSBC MSCI South Africa UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMAF", name: "HSBC MSCI AC Far East ex Japan UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMES", name: "HSBC MSCI Emerging Markets UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "HMWA", name: "HSBC MSCI World UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "SMEA", name: "iShares Core MSCI Europe UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "IMEA", name: "iShares Core MSCI EM IMI UCITS Acc", kind: "etf", region: "GLOBAL" },
  { symbol: "CEUU", name: "iShares Core MSCI EMU UCITS USD Hdg", kind: "etf", region: "GLOBAL" },
  { symbol: "CEMA", name: "iShares MSCI EM Asia UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "IDSE", name: "iShares MSCI Europe SRI UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "INRA", name: "iShares MSCI World Islamic UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "LTAM", name: "iShares MSCI EM Latin America UCITS", kind: "etf", region: "GLOBAL" },
  { symbol: "LAMT", name: "iShares MSCI EM Latin America UCITS Acc", kind: "etf", region: "GLOBAL" },
];

export const SIC_ALL: SicItem[] = [...SIC_STOCKS, ...SIC_ETFS, ...SIC_UCITS];

export function searchSic(q: string, kind?: SicKind | "ALL" | "ucits"): SicItem[] {
  const rawNeedle = normalizeSearchText(q);
  const canonicalNeedle = normalizeYahooSymbol(rawNeedle);
  const needles = [...new Set([rawNeedle, canonicalNeedle])];
  const pool =
    kind === "stock"
      ? SIC_STOCKS
      : kind === "etf"
      ? [...SIC_ETFS, ...SIC_UCITS]
      : kind === "ucits"
      ? SIC_UCITS
      : SIC_ALL;
  if (!rawNeedle) return pool;
  return pool.filter((item) =>
    needles.some(
      (needle) =>
        item.symbol.toUpperCase().includes(needle) ||
        normalizeSearchText(item.name).includes(needle)
    )
  );
}

export function isSicSymbol(symbol: string): boolean {
  const s = normalizeYahooSymbol(symbol).replace(/\.MX$/, "");
  return SIC_ALL.some((i) => i.symbol.toUpperCase() === s);
}
