/* eslint-disable @typescript-eslint/no-require-imports -- Standalone Node browser test, not application code. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const BASE = process.env.TEST_BASE_URL || 'http://localhost:3000';
(async () => {
 const browser = await chromium.launch({executablePath: process.env.CHROMIUM_PATH || undefined, args: ["--no-sandbox"], headless:true});
 const context = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});
 await context.addInitScript(() => {localStorage.setItem('marketpulse_watchlist',JSON.stringify(['AAPL']));localStorage.setItem('mxcg_legal_banner_v1','1');localStorage.setItem('mxcg_sec_banner_dismiss','9999999999999');});
 await context.route('**/api/**', route => {
  const url=route.request().url();
  const quote={symbol:'AAPL',name:'Apple',region:'US',currency:'USD',price:200,changePercent:1};
  let body = url.includes('/search?') ? {results:[{symbol:'AAPL',name:'Apple'},{symbol:'AMXL.MX',name:'América Móvil'}]} : url.includes('/indices') ? {indices:[{...quote,symbol:'^GSPC'},{...quote,symbol:'^DJI'},{...quote,symbol:'^MXX'}]} : {quotes:[quote],usdMxn:18,results:[]};
  return route.fulfill({json:body});
 });
 const page=await context.newPage();
 await page.goto(`${BASE}/sic`);
 const tabs=page.getByRole('tab'); await tabs.first().waitFor();
 await tabs.first().focus();await page.keyboard.press('ArrowRight');assert.equal(await tabs.nth(1).getAttribute('aria-selected'),'true');
 await page.keyboard.press('End');assert.equal(await tabs.nth(2).getAttribute('aria-selected'),'true');
 await page.keyboard.press('Home');assert.equal(await tabs.first().getAttribute('aria-selected'),'true');
 const panel=page.getByRole('tabpanel');await panel.waitFor();
 await panel.dispatchEvent('touchstart',{touches:[{identifier:1,clientX:270,clientY:120}],changedTouches:[{identifier:1,clientX:270,clientY:120}]});
 await panel.dispatchEvent('touchend',{touches:[],changedTouches:[{identifier:1,clientX:80,clientY:125}]});
 assert.equal(await tabs.nth(1).getAttribute('aria-selected'),'true');
 console.log('PASS tabs: arrows, Home/End, touch swipe');
 await page.goto(`${BASE}/watchlist`);
 const combo=page.getByRole('combobox');await combo.fill('apple');await page.getByRole('option').first().waitFor();
 await combo.press('ArrowDown');assert.ok(await combo.getAttribute('aria-activedescendant'));
 await combo.press('End');assert.equal(await page.getByRole('option').nth(1).getAttribute('aria-selected'),'true');
 await combo.press('Escape');assert.equal(await combo.getAttribute('aria-expanded'),'false');
 await combo.press('ArrowDown');assert.equal(await combo.getAttribute('aria-expanded'),'true');
 await page.locator('h1').click();
 assert.equal(await combo.getAttribute('aria-expanded'),'false');
 console.log('PASS combobox: typing, active option, End, Escape, outside dismissal');
 const toggle=page.getByRole('button',{name:'Mostrar acciones de AAPL'});await toggle.waitFor();
 assert.equal(await page.getByRole('button',{name:'Eliminar AAPL'}).count(),0);
 await toggle.click();await page.getByRole('button',{name:'Eliminar AAPL'}).waitFor();
 await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Eliminar AAPL'}).count(),0);
 console.log('PASS actions: explicit open, inert hidden action, Escape focus return');
 const content=page.locator('.ui-swipe__content').first(); await content.scrollIntoViewIfNeeded();
 const rect=await content.boundingBox();
 const cdp=await context.newCDPSession(page);
 const x=rect.x+rect.width-24, y=rect.y+rect.height/2;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-70,y:y+2}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-100,y:y+2}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await page.getByRole('button',{name:'Eliminar AAPL'}).waitFor();
 await page.getByRole('button',{name:'Cerrar acciones de AAPL'}).click();
 console.log('PASS real Chromium touch drag reveals actions without activating delete');
 const verticalRect=await content.boundingBox();
 const vx=verticalRect.x+verticalRect.width-24, vy=verticalRect.y+verticalRect.height/2;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:vx,y:vy}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:vx-4,y:vy-65}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert.equal(await page.getByRole('button',{name:'Eliminar AAPL'}).count(),0);
 await content.scrollIntoViewIfNeeded();
 const link=content.locator('a'); const lr=await link.boundingBox();
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:lr.x+lr.width/2,y:lr.y+15}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:lr.x+lr.width/2-65,y:lr.y+16}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert.equal(await page.getByRole('button',{name:'Eliminar AAPL'}).count(),0);
 assert.ok(page.url().endsWith('/watchlist'));
 console.log('PASS vertical touch and nested link do not reveal or activate actions');


 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.goto(`${BASE}/metrics`);
 const filters=page.getByRole('button',{name:'Filtros',exact:true});await filters.click();assert.equal(await filters.getAttribute('aria-expanded'),'false');
 assert.equal(await page.getByRole('spinbutton').count(),0);
 await filters.click();assert.ok(await page.getByRole('spinbutton').count()>0);
 console.log('PASS disclosure: expanded and inert fields');
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`${BASE}/sic`);await page.getByRole('tab').first().waitFor();
 assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 console.log('PASS mobile width and reduced motion');
 await page.goto(`${BASE}/`);await page.locator('.ui-card-carousel').waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.ok(await page.locator('.ui-card-carousel').evaluate(el=>el.scrollWidth>el.clientWidth));
 console.log('PASS mobile carousel overflows locally, not globally');
 await page.setViewportSize({width:1280,height:900});
 assert.equal(await page.locator('.ui-card-carousel').evaluate(el=>getComputedStyle(el).display),'grid');
 console.log('PASS desktop carousel becomes grid');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
