export type MxKind = "stock" | "etf" | "fibra" | "bond_etf";
export type MxItem = { symbol: string; name: string; kind: MxKind; venue: "BMV" | "BIVA" | "SIC" | "BMV/BIVA" };
const RAW_STOCKS: Array<[string, string, MxKind, MxItem["venue"]]> = [["AMXL.MX", "América Móvil", "stock", "BMV/BIVA"], ["WALMEX.MX", "Walmart de México", "stock", "BMV/BIVA"], ["GFNORTEO.MX", "GFNorte (Banorte)", "stock", "BMV/BIVA"], ["GMEXICOB.MX", "Grupo México", "stock", "BMV/BIVA"], ["FEMSAUBD.MX", "FEMSA", "stock", "BMV/BIVA"], ["BIMBOA.MX", "Bimbo", "stock", "BMV/BIVA"], ["CEMEXCPO.MX", "Cemex CPO", "stock", "BMV/BIVA"], ["TLEVISACPO.MX", "Televisa CPO", "stock", "BMV/BIVA"], ["KIMBERA.MX", "Kimberly-Clark de México", "stock", "BMV/BIVA"], ["ASURB.MX", "ASUR", "stock", "BMV/BIVA"], ["GAPB.MX", "GAP", "stock", "BMV/BIVA"], ["OMAB.MX", "OMA", "stock", "BMV/BIVA"], ["GFINBURO.MX", "Inbursa", "stock", "BMV/BIVA"], ["BOLSAA.MX", "Bolsa Mexicana de Valores", "stock", "BMV/BIVA"], ["GCARSOA1.MX", "Grupo Carso", "stock", "BMV/BIVA"], ["GENTERA.MX", "Gentera", "stock", "BMV/BIVA"], ["ALSEA.MX", "Alsea", "stock", "BMV/BIVA"], ["AC.MX", "Arca Continental", "stock", "BMV/BIVA"], ["KOFUBL.MX", "Coca-Cola FEMSA", "stock", "BMV/BIVA"], ["BBAJIOO.MX", "Banco del Bajío", "stock", "BMV/BIVA"], ["Q.MX", "Qualitas", "stock", "BMV/BIVA"], ["VESTA.MX", "Vesta", "stock", "BMV/BIVA"]];
const RAW_FIBRAS: Array<[string, string, MxKind, MxItem["venue"]]> = [["FUNO11.MX", "Fibra UNO", "fibra", "BMV/BIVA"], ["FMTY14.MX", "Fibra Mty", "fibra", "BMV/BIVA"], ["DANHOS13.MX", "Fibra Danhos", "fibra", "BMV/BIVA"], ["FIBRAPL14.MX", "Fibra Prologis", "fibra", "BMV/BIVA"], ["TERRA13.MX", "Fibra Terra", "fibra", "BMV/BIVA"], ["FSHOP13.MX", "Fibra Shop", "fibra", "BMV/BIVA"], ["NEXT25.MX", "Fibra NEXT", "fibra", "BMV/BIVA"], ["FEXI21.MX", "Fibra EXI", "fibra", "BMV/BIVA"]];
const RAW_ETFS: Array<[string, string, MxKind, MxItem["venue"]]> = [["NAFTRAC.MX", "iShares NAFTRAC (IPC)", "etf", "BMV/BIVA"], ["VMEX.MX", "Vanguard FTSE BIVA México", "etf", "BMV/BIVA"], ["IVVPESO.MX", "iShares S&P 500 MXN Hedged", "etf", "BMV/BIVA"]];
const RAW_BONDS: Array<[string, string, MxKind, MxItem["venue"]]> = [["LQD", "iShares Corp. grado inversión", "bond_etf", "SIC"], ["HYG", "iShares High Yield", "bond_etf", "SIC"], ["BND", "Vanguard Total Bond", "bond_etf", "SIC"]];
const map = (rows: Array<[string, string, MxKind, MxItem["venue"]]>): MxItem[] => rows.map(([symbol, name, kind, venue]) => ({ symbol, name, kind, venue }));
export const MX_LOCAL_STOCKS = map(RAW_STOCKS);
export const MX_FIBRAS = map(RAW_FIBRAS);
export const MX_LOCAL_ETFS = map(RAW_ETFS);
export const MX_BOND_ETFS = map(RAW_BONDS);
export const MX_UNIVERSE: MxItem[] = [...MX_LOCAL_STOCKS, ...MX_FIBRAS, ...MX_LOCAL_ETFS, ...MX_BOND_ETFS];
export function normalizeMxSymbol(s: string) { return s.trim().toUpperCase(); }
export function isInMxUniverse(symbol: string) { const s = normalizeMxSymbol(symbol); return MX_UNIVERSE.some((i) => i.symbol === s || i.symbol.replace(/\.MX$/, "") === s.replace(/\.MX$/, "")); }
export function searchMxUniverse(q: string): MxItem[] { const n = q.trim().toUpperCase(); if (!n) return []; return MX_UNIVERSE.filter((i) => i.symbol.includes(n) || i.name.toUpperCase().includes(n)); }
export const searchMx = searchMxUniverse;
export function mxUniverseStats() { return { stocks: MX_LOCAL_STOCKS.length, fibras: MX_FIBRAS.length, etfs: MX_LOCAL_ETFS.length, bonds: MX_BOND_ETFS.length, total: MX_UNIVERSE.length }; }
